export const ADVANCE_FORM = [
  {
    label: "Number",
    placeholder: "Enter number",
    type: "text",
    className: "base-text",
    name: "numberOne",
  },
  {
    label: "Number",
    placeholder: "Enter number",
    type: "text",
    className: "base-text",
    name: "numberTwo",
  },
  {
    label: "Year from Past",
    placeholder: "Enter past year",
    type: "number",
    className: "base-text",
    name: "yearFromPast",
  },
  {
    label: "Noun",
    placeholder: "Enter noun",
    type: "text",
    name: "noun",
    className: "base-text",
  },
  {
    label: "Food",
    name: "foodOne",
    placeholder: "Enter food name",
    type: "text",
    className: "base-text",
  },
  {
    label: "Food",
    name: "foodTwo",
    placeholder: "Enter food name",
    type: "text",
    className: "base-text",
  },
  {
    label: "Animal",
    name: "animal",
    placeholder: "Enter animal name",
    type: "text",
    className: "base-text",
  },
  {
    label: "Object",
    name: "object",
    placeholder: "Enter object name",
    type: "text",
    className: "base-text",
  },
  {
    label: "Place",
    name: "place",
    placeholder: "Enter name of place",
    type: "text",
    className: "base-text",
  },
  {
    label: "School Subject",
    placeholder: "Enter school subject",
    type: "text",
    name: "schoolSubjectOne",
    className: "base-text",
  },
  {
    label: "School Subject",
    placeholder: "Enter school subject",
    type: "text",
    name: "schoolSubjectTwo",
    className: "base-text",
  },
  {
    label: "Name",
    name: "name",
    placeholder: "Enter name",
    type: "text",
    className: "base-text",
  },
  {
    label: "Adjective",
    name: "adjectiveOne",
    placeholder: "Enter adjective",
    type: "text",
    className: "base-text",
  },
  {
    label: "Adjective",
    name: "adjectiveTwo",
    placeholder: "Enter adjective",
    type: "text",
    className: "base-text",
  },
  {
    label: "Adjective",
    name: "adjectiveThree",
    placeholder: "Enter adjective",
    type: "text",
    className: "base-text",
  },
];
